import { diseaseData, type Severity } from "./disease-data"

const DISEASE_RULES: Record<string, Record<string, string>> = {
  Jaundice: {
    headache: "no",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "no",
  },
  Alzheimers: {
    headache: "no",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "no",
    restlessness: "yes",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "no",
    blurred_vision: "no",
  },
  Arthritis: {
    headache: "no",
    back_pain: "yes",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "no",
    blurred_vision: "no",
  },
  Tuberculosis: {
    headache: "no",
    back_pain: "no",
    chest_pain: "yes",
    cough: "yes",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "yes",
    nausea: "no",
    blurred_vision: "no",
  },
  Asthma: {
    headache: "no",
    back_pain: "no",
    chest_pain: "yes",
    cough: "yes",
    fainting: "no",
    sore_throat: "no",
    fatigue: "no",
    restlessness: "yes",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "no",
    blurred_vision: "no",
  },
  Sinusitis: {
    headache: "yes",
    back_pain: "no",
    chest_pain: "no",
    cough: "yes",
    fainting: "no",
    sore_throat: "yes",
    fatigue: "no",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "no",
    nausea: "no",
    blurred_vision: "no",
  },
  Epilepsy: {
    headache: "no",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "yes",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "no",
    blurred_vision: "no",
  },
  "Heart Disease": {
    headache: "no",
    back_pain: "no",
    chest_pain: "yes",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "no",
  },
  Diabetes: {
    headache: "no",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "yes",
  },
  Glaucoma: {
    headache: "yes",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "no",
    restlessness: "no",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "yes",
  },
  Hyperthyroidism: {
    headache: "no",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "yes",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "no",
  },
  "Heat Stroke": {
    headache: "yes",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "yes",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "yes",
    nausea: "yes",
    blurred_vision: "no",
  },
  Hypothermia: {
    headache: "no",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "yes",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "yes",
    fever: "no",
    sunken_eyes: "yes",
    nausea: "no",
    blurred_vision: "no",
  },
  Bronchitis: {
    headache: "no",
    back_pain: "no",
    chest_pain: "yes",
    cough: "yes",
    fainting: "no",
    sore_throat: "yes",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "no",
    nausea: "no",
    blurred_vision: "no",
  },
  Pneumonia: {
    headache: "yes",
    back_pain: "no",
    chest_pain: "yes",
    cough: "yes",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "no",
  },
  Migraine: {
    headache: "yes",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "yes",
  },
  Gastritis: {
    headache: "no",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "no",
  },
  "Urinary Tract Infection": {
    headache: "yes",
    back_pain: "yes",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "no",
  },
  Anemia: {
    headache: "yes",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "yes",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "yes",
    nausea: "yes",
    blurred_vision: "yes",
  },
  "Acute Bronchial Asthma": {
    headache: "no",
    back_pain: "no",
    chest_pain: "yes",
    cough: "yes",
    fainting: "yes",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "yes",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "no",
    blurred_vision: "no",
  },
  Hypertension: {
    headache: "yes",
    back_pain: "no",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "no",
    blurred_vision: "yes",
  },
  "Acute Myocardial Infarction": {
    headache: "no",
    back_pain: "no",
    chest_pain: "yes",
    cough: "no",
    fainting: "yes",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "yes",
    low_body_temp: "no",
    fever: "no",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "no",
  },
  Colitis: {
    headache: "no",
    back_pain: "yes",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "yes",
    nausea: "yes",
    blurred_vision: "no",
  },
  Meningitis: {
    headache: "yes",
    back_pain: "yes",
    chest_pain: "no",
    cough: "no",
    fainting: "yes",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "yes",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "no",
  },
  Dengue: {
    headache: "yes",
    back_pain: "yes",
    chest_pain: "no",
    cough: "no",
    fainting: "no",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "no",
    nausea: "yes",
    blurred_vision: "no",
  },
  Malaria: {
    headache: "yes",
    back_pain: "yes",
    chest_pain: "no",
    cough: "no",
    fainting: "yes",
    sore_throat: "no",
    fatigue: "yes",
    restlessness: "no",
    low_body_temp: "no",
    fever: "yes",
    sunken_eyes: "yes",
    nausea: "yes",
    blurred_vision: "no",
  },
}

function countMatchingSymptoms(userSymptoms: Record<string, string>, ruleSymptoms: Record<string, string>): number {
  let count = 0
  for (const [key, value] of Object.entries(ruleSymptoms)) {
    if (userSymptoms[key] === value && value === "yes") {
      count += 2 // Weight 'yes' matches higher
    } else if (userSymptoms[key] === value && value === "no") {
      count += 1 // Lower weight for 'no' matches
    }
  }
  return count
}

export function findMostProbableDisease(symptoms: Record<string, string>): {
  disease: string
  confidence: number
  severity: Severity
  urgency: string
} {
  let maxScore = 0
  let mostProbableDisease = "Unknown Condition"

  // Check for exact matches first
  for (const [disease, rules] of Object.entries(DISEASE_RULES)) {
    const matches = Object.entries(rules).every(([key, value]) => symptoms[key] === value)
    if (matches) {
      const diseaseInfo = diseaseData[disease as keyof typeof diseaseData]
      return {
        disease,
        confidence: 100,
        severity: diseaseInfo.severity,
        urgency: diseaseInfo.urgency,
      }
    }
  }

  // If no exact match, find best partial match
  for (const [disease, rules] of Object.entries(DISEASE_RULES)) {
    const score = countMatchingSymptoms(symptoms, rules)
    if (score > maxScore) {
      maxScore = score
      mostProbableDisease = disease
    }
  }

  const diseaseInfo = diseaseData[mostProbableDisease as keyof typeof diseaseData]
  const confidence = Math.min(Math.round((maxScore / 26) * 100), 95) // Cap at 95%

  return {
    disease: mostProbableDisease,
    confidence,
    severity: diseaseInfo.severity,
    urgency: diseaseInfo.urgency,
  }
}
